### ISSUE TITLE
Error produced when using metered_savings() on hourly data.

### ISSUE THREAD

**Issue by Viktoriya-An** [openeemeter/eemeter#398]
Hi, I am trying to run an example in the Tutorial (http://eemeter.openee.io/tutorial.html) for the hourly data (Quickstart for CalTRACK Hourly). Please advise. Thank you!

1. The error occurs when running the following code:
metered_savings_dataframe, error_bands = eemeter.metered_savings(
    baseline_model, reporting_meter_data,
    temperature_data, with_disaggregated=True
)

Traceback (most recent call last):

File "<ipython-input-23-1e2a337427b3>", line 3, in <module> temperature_data, with_disaggregated=True
File "C:\Users\xxx\anaconda3\lib\site-packages\eemeter\derivatives.py", line 227, in metered_savings prediction_index, temperature_data, **predict_kwargs
File "C:\Users\xxx\anaconda3\lib\site-packages\eemeter\caltrack\hourly.py", line 191, in predict
    return self.model.predict(prediction_index, temperature_data, **kwargs)
File "C:\Users\xxx\anaconda3\lib\site-packages\eemeter\segmentation.py", line 221, in predict
    prediction = segment_model.predict(segmented_data) * segmented_data.weight
File "C:\Users\xxx\anaconda3\lib\site-packages\eemeter\segmentation.py", line 98, in predict
    columns={0: "predicted_usage"}
TypeError: rename() got an unexpected keyword argument 'columns'

2.Version string of eemeter, pandas, and their dependencies: 
eemeter version : 2.9.2
pandas version : 1.0.1
python           : 3.7.6

**Comment by Viktoriya-An** [comment]
The issue has been resolved by using Python 3.6 and pandas 0.23.4.
